const Food = require('../models/foodModel');

const addToFavorites = async (req, res) => {
  try {
    const { idMeal,
      dateModified,
      strArea,
      strCategory,
      strCreativeCommonsConfirmed,
      strDrinkAlternate,
      strImageSource,
      strIngredient1,
      strIngredient2,
      strIngredient3,
      strIngredient4,
      strIngredient5,
      strIngredient6,
      strIngredient7,
      strIngredient8,
      strIngredient9,
      strIngredient10,
      strIngredient11,
      strIngredient12,
      strIngredient13,
      strIngredient14,
      strIngredient15,
      strIngredient16,
      strIngredient17,
      strIngredient18,
      strIngredient19,
      strIngredient20,
      strInstructions,
      strMeal,
      strMealThumb,
      strMeasure1,
      strMeasure2,
      strMeasure3,
      strMeasure4,
      strMeasure5,
      strMeasure6,
      strMeasure7,
      strMeasure8,
      strMeasure9,
      strMeasure10,
      strMeasure11,
      strMeasure12,
      strMeasure13,
      strMeasure14,
      strMeasure15,
      strMeasure16,
      strMeasure17,
      strMeasure18,
      strMeasure19,
      strMeasure20,
      strSource,
      strTags,
      strYoutube,
      email } = req.body; // Extract the relevant food details

    const newFood = new Food({
      idMeal,
      dateModified,
      strArea,
      strCategory,
      strCreativeCommonsConfirmed,
      strDrinkAlternate,
      strImageSource,
      strIngredient1,
      strIngredient2,
      strIngredient3,
      strIngredient4,
      strIngredient5,
      strIngredient6,
      strIngredient7,
      strIngredient8,
      strIngredient9,
      strIngredient10,
      strIngredient11,
      strIngredient12,
      strIngredient13,
      strIngredient14,
      strIngredient15,
      strIngredient16,
      strIngredient17,
      strIngredient18,
      strIngredient19,
      strIngredient20,
      strInstructions,
      strMeal,
      strMealThumb,
      strMeasure1,
      strMeasure2,
      strMeasure3,
      strMeasure4,
      strMeasure5,
      strMeasure6,
      strMeasure7,
      strMeasure8,
      strMeasure9,
      strMeasure10,
      strMeasure11,
      strMeasure12,
      strMeasure13,
      strMeasure14,
      strMeasure15,
      strMeasure16,
      strMeasure17,
      strMeasure18,
      strMeasure19,
      strMeasure20,
      strSource,
      strTags,
      strYoutube,
      email
    })

    await newFood.save(); // Save the new food document to the "foods" collection

    res.status(200).json({ message: 'Food added to favorites successfully' });
    console.log("Sent!")
    console.log(newFood);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: 'Failed to add food to favorites' });
  }
};

module.exports = addToFavorites;
